import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function POST(request: NextRequest) {
  console.log('[POST /api/workouts/assign] Called')
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { data: profile } = await supabase
      .from('profiles')
      .select('organization_id')
      .eq('id', user.id)
      .single()

    if (!profile?.organization_id) {
      return NextResponse.json({ error: 'No organization' }, { status: 403 })
    }

    const body = await request.json()
    const { template_id, member_id } = body

    if (!template_id || !member_id) {
      return NextResponse.json({ error: 'Template and member are required' }, { status: 400 })
    }

    console.log('[Assign] Template:', template_id, 'Member:', member_id)

    // Archive any existing active assignment for this template + member
    await supabase
      .from('workout_assignments')
      .update({ status: 'archived' })
      .eq('template_id', template_id)
      .eq('member_id', member_id)
      .eq('status', 'active')

    // Create new assignment (share_token auto-generated by DB default)
    const { data: assignment, error } = await supabase
      .from('workout_assignments')
      .insert({
        organization_id: profile.organization_id,
        template_id,
        member_id,
        assigned_by: user.id,
        status: 'active',
      })
      .select('id, share_token')
      .single()

    if (error || !assignment) {
      console.log('[Assign] Error:', error?.message)
      return NextResponse.json({ error: error?.message ?? 'Failed to assign' }, { status: 500 })
    }

    console.log('[Assign] Done ✅ Token:', assignment.share_token)
    return NextResponse.json({ share_token: assignment.share_token }, { status: 201 })

  } catch (err) {
    console.error('[Assign] Error:', err)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}
